<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>tmpl</string>
    </array>
    <key>foldingStartMarker</key>
    <string>^#(block|def)</string>
    <key>foldingStopMarker</key>
    <string>^#end (block|def)</string>
    <key>keyEquivalent</key>
    <string>^~h</string>
    <key>name</key>
    <string>Yelp Cheetah</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>##.*$</string>
            <key>name</key>
            <string>comment.line.cheetah</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>(#(end )?(block|def|call|with))( [$a-zA-Z_\.][a-zA-Z0-9_\.]*)?</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>storage.type.cheetah</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>support.other.cheetah</string>
                </dict>
                <key>4</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.cheetah</string>
                </dict>
            </dict>
            <key>end</key>
            <string>$</string>
            <key>name</key>
            <string>meta.declaration.cheetah</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\$[a-zA-Z\_\.\-\s\d]*</string>
            <key>name</key>
            <string>variable.other.cheetah</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.other.include.import.cheetah</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.other.include.as.cheetah</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.cheetah</string>
                </dict>
            </dict>
            <key>match</key>
            <string>^(#import)\s+[a-zA-Z_\.\,][a-zA-Z0-9_\.\,]*\s+(as)?</string>
            <key>name</key>
            <string>meta.other.include.cheetah</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.other.include.from.cheetah</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>keyword.other.include.import.cheetah</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>keyword.other.include.as.cheetah</string>
                </dict>
            </dict>
            <key>match</key>
            <string>^(#from)\s+[a-zA-Z_][a-zA-Z0-9_\.\,]*\s+(import)\s+[a-zA-Z_][a-zA-Z0-9_\,\.]*\s+(as)?</string>
            <key>name</key>
            <string>meta.other.include.cheetah</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.other.extends.cheetah</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.other.inherited-class</string>
                </dict>
            </dict>
            <key>match</key>
            <string>^(#extends)\s+([a-zA-Z_][a-zA-Z0-9_\.]*)</string>
            <key>name</key>
            <string>meta.other.extends.cheetah</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>keyword.other.implements.cheetah</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.cheetah</string>
                </dict>
            </dict>
            <key>match</key>
            <string>^(#implements)\s+([a-zA-Z_][a-zA-Z0-9_]*)</string>
            <key>name</key>
            <string>meta.other.implements.cheetah</string>
        </dict>
        <dict>
            <key>match</key>
            <string>#(end )?(for|if|elif|try|while)\b</string>
            <key>name</key>
            <string>keyword.control.cheetah</string>
        </dict>
        <dict>
            <key>match</key>
            <string>#(assert|break|continue|else|except|finally|pass|raise)\b</string>
            <key>name</key>
            <string>keyword.control.cheetah</string>
        </dict>
        <dict>
            <key>match</key>
            <string>#(attr|del|filter|silent|py|super|return)\b</string>
            <key>name</key>
            <string>keyword.other.cheetah</string>
        </dict>
        <dict>
            <key>match</key>
            <string>#set(\s+global)?</string>
            <key>name</key>
            <string>keyword.other.cheetah</string>
        </dict>
        <dict>
            <key>match</key>
            <string>#slurp</string>
            <key>name</key>
            <string>keyword.directive.cheetah</string>
        </dict>
        <dict>
            <key>match</key>
            <string>^#(end )?(compiler-settings)\b</string>
            <key>name</key>
            <string>support.other.directive.cheetah</string>
        </dict>
        <dict>
            <key>comment</key>
            <string>Since html is valid in Cheetah templates include the html patterns</string>
            <key>include</key>
            <string>text.html.basic</string>
        </dict>
    </array>
    <key>scopeName</key>
    <string>text.html.yelp_cheetah</string>
    <key>uuid</key>
    <string>28b4fb67-f1de-473d-8cf8-5b826664a324</string>
</dict>
</plist>
